### PR TITLE
Custom configuration to override the generated OpenAPI

### PR DESCRIPTION
**Pull request by crashdump**
Implements #120. This simple approach to implementing an `override` config has a couple of drawbacks: 

1. It does not enforce compliance with the OAS specs
2. Only supports a _raw_ merging strategy

On the plus side, it's very simple.

### CODE REVIEW

**Comment by crashdump** [comment]
@dsinghvi thoughts? Is this approach sufficient or would you prefer validation the input conforms to OAS3?

**Comment by dsinghvi** [comment]
@crashdump this is great -- the only issue that i can see with the approach is it would be nice if you "merged" instead of overriding keys. 

Somesort of deep merge like https://stackoverflow.com/questions/27936772/how-to-deep-merge-instead-of-shallow-merge, or using lodash (https://blog.yogeshchavan.dev/how-to-merge-deeply-nested-objects-in-javascript#using-lodash-merge) would be better

**Comment by dsinghvi** [comment]
Once you update the merge strategy would be okay to merge

**Comment by crashdump** [comment]
Thanks for the suggestions, @dsinghvi. I've gone down the route of Lodash since it's already once of the project's dependencies!

**Pull request merged**
